[project]
name = "mcp-101"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.6.3",
    "fastmcp>=2.3.4",
    "mcp>=1.8.1",
    "pydantic-ai>=0.2.4",
    "rich>=14.0.0",
]
